#!/bin/tcsh

# Set command line preferences
set autolist

# Set aliases
alias rm rm -i
alias mv mv -i
alias ls ls -G
alias ll ls -la

# Set prompt
alias __git_changed 'if (`sh -c "git diff --shortstat 2> /dev/null | tail -n1"` !=  "") echo "*"'
alias __git_branch_cmd 'sh -c "git branch --no-color 2> /dev/null" | sed -e "/^[^*]/d" -e "s/* \(.*\)/(\1`__git_changed`) /"'
alias precmd 'set prompt = "%{\033[32;1m%}%n%{\033[0m%}@%{\033[32m%}%m%{\033[0m%}: %{\033[34m%}%/%{\033[0m%} `__git_branch_cmd`%#%{\033[0m%} "'

# Set man page colors for tcsh/csh
setenv PAGER "less -IRs"
setenv LESS_TERMCAP_mb `echotc AF 0 1`
setenv LESS_TERMCAP_md `echotc AF 0 2`
setenv LESS_TERMCAP_me `echotc me`
setenv LESS_TERMCAP_so `echotc AF 0 3; echotc AB 0 1`
setenv LESS_TERMCAP_se `echotc me`
setenv LESS_TERMCAP_us `echotc AF 0 6`
setenv LESS_TERMCAP_ue `echotc me`

# Set environment variables for Homebrew (located in custom /usr/local/homebrew)
setenv PATH      /usr/local/homebrew/sbin:/usr/local/homebrew/bin:${PATH}
set    MANPATH = `manpath`
setenv MANPATH   /usr/local/homebrew/share/man:${MANPATH}

# Set environment variables for the Homebrew version of Ruby
setenv PATH      /usr/local/homebrew/opt/ruby/bin:${PATH}

# Set environment variables for RubyGems (located in custom /usr/local/gem)
setenv GEM_HOME /usr/local/gem
setenv PATH     ${GEM_HOME}/bin:${PATH}
